"""Add settings and tools models

Revision ID: f16a6234c1e9
Revises: 56b651380434
Create Date: 2026-06-23 23:35:34.604725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16a6234c1e9'
down_revision: Union[str, None] = '56b651380434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_site_settings_key'), 'site_settings', ['key'], unique=False)
    op.create_table('tool_settings',
    sa.Column('tool_id', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('guest_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_index(op.f('ix_tool_settings_tool_id'), 'tool_settings', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_settings_tool_id'), table_name='tool_settings')
    op.drop_table('tool_settings')
    op.drop_index(op.f('ix_site_settings_key'), table_name='site_settings')
    op.drop_table('site_settings')
    # ### end Alembic commands ###
