import React from "react";
import {
  AlignLeft,
  ArrowRightLeft,
  ArrowUpDown,
  Clock,
  Code,
  Crop,
  Download,
  EyeOff,
  FileCode,
  FileJson,
  FileOutput,
  FileText,
  FileType,
  Fingerprint,
  GitCompareArrows,
  Globe,
  Hash,
  Heading,
  ImageIcon,
  KeyRound,
  Layers,
  Link2,
  ListX,
  Lock,
  Map,
  Maximize2,
  Minimize2,
  Palette,
  PenLine,
  QrCode,
  Regex,
  RotateCw,
  Ruler,
  Scissors,
  Search,
  Share2,
  Stamp,
  Tags,
  TextCursorInput,
  Type,
  Wand2,
} from "lucide-react";
import type { ToolCategory, ToolColorTheme } from "@/lib/tools";

const themeIconColor: Record<ToolColorTheme, string> = {
  blue: "text-blue-500",
  rose: "text-rose-500",
  violet: "text-violet-500",
  amber: "text-amber-500",
  fuchsia: "text-fuchsia-500",
  indigo: "text-indigo-500",
};

const HREF_ICON_COMPONENTS: Record<string, React.ComponentType<{ className?: string }>> = {
  "/tools/image/remove-bg": Wand2,
  "/tools/image/convert/jpg-to-png": ArrowRightLeft,
  "/tools/image/convert/png-to-jpg": ArrowRightLeft,
  "/tools/image/convert/webp-to-jpg": ArrowRightLeft,
  "/tools/image/convert/webp-to-png": ArrowRightLeft,
  "/tools/image/convert/heic-to-jpg": ArrowRightLeft,
  "/tools/image/convert/heic-to-png": ArrowRightLeft,
  "/tools/image/compress": Minimize2,
  "/tools/image/resize": Maximize2,
  "/tools/image/crop": Crop,
  "/tools/image/watermark": Stamp,
  "/tools/image/rotate-flip": RotateCw,
  "/tools/image/to-pdf": FileText,
  "/tools/image/redact": EyeOff,
  "/tools/pdf/merge": Layers,
  "/tools/pdf/compress": Minimize2,
  "/tools/pdf/split": Scissors,
  "/tools/pdf/to-images": ImageIcon,
  "/tools/pdf/to-word": FileType,
  "/tools/pdf/word-to-pdf": FileOutput,
  "/tools/pdf/watermark": Stamp,
  "/tools/pdf/rotate": RotateCw,
  "/tools/pdf/page-numbers": Hash,
  "/tools/pdf/to-text": FileText,
  "/tools/pdf/reorder": ArrowUpDown,
  "/tools/pdf/sign": PenLine,
  "/tools/pdf/images-to-pdf": ImageIcon,
  "/tools/downloader": Download,
  "/tools/developer/json-formatter": FileJson,
  "/tools/developer/uuid-generator": Fingerprint,
  "/tools/developer/base64": Hash,
  "/tools/developer/timestamp-converter": Clock,
  "/tools/developer/url-encode": Link2,
  "/tools/developer/hash-generator": Hash,
  "/tools/developer/minifier": Minimize2,
  "/tools/developer/lorem-ipsum": Type,
  "/tools/developer/color-converter": Palette,
  "/tools/developer/jwt-decoder": KeyRound,
  "/tools/developer/regex-tester": Regex,
  "/tools/developer/yaml-formatter": FileCode,
  "/tools/developer/password-generator": Lock,
  "/tools/developer/qr-code": QrCode,
  "/tools/seo/meta-tags": Tags,
  "/tools/seo/sitemap": Map,
  "/tools/seo/robots": Code,
  "/tools/seo/canonical-checker": Link2,
  "/tools/seo/text-diff": GitCompareArrows,
  "/tools/seo/slug-generator": TextCursorInput,
  "/tools/seo/word-counter": AlignLeft,
  "/tools/seo/remove-duplicate-lines": ListX,
  "/tools/seo/og-preview": Share2,
  "/tools/seo/meta-description": Ruler,
  "/tools/seo/heading-analyzer": Heading,
  "/tools/seo/hreflang": Globe,
};

const CATEGORY_ICON_COMPONENTS: Record<ToolCategory, React.ComponentType<{ className?: string }>> = {
  image: ImageIcon,
  pdf: FileText,
  developer: Code,
  seo: Search,
  downloader: Download,
};

export function getToolListIcon(href: string, category: ToolCategory, colorTheme: ToolColorTheme) {
  const Comp = HREF_ICON_COMPONENTS[href] ?? CATEGORY_ICON_COMPONENTS[category];
  return <Comp className={`h-6 w-6 ${themeIconColor[colorTheme]}`} />;
}

export function getToolPageIcon(href: string, category: ToolCategory, colorTheme: ToolColorTheme) {
  const Comp = HREF_ICON_COMPONENTS[href] ?? CATEGORY_ICON_COMPONENTS[category];
  return <Comp className={`h-10 w-10 ${themeIconColor[colorTheme]}`} />;
}
